name: Deploy Slidev
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run:  npm i -g @slidev/cli
      - name: pwd
        run: pwd
      - name: Build
        run: slidev build slide01/slides.md --base /slidevtest/slide02/ --out dist/slide02/
        working-directory: ./
      - name: check
        run: ls ./
        working-directory: ./
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
