name: Deploy Slidev
on:
  push:
    paths:
      - '**/**'
      - '!README.md'
      - '!docs/**'
      - '!.github/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install slidev
        run:  npm i -g @slidev/cli

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          dir_names: "true"

      # 変更のあったディレクトリのトップレベルのみ抽出
      - name: List Changed Directory
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}"|tr " " "\n"|grep -v "^\."|cut -d/ -f1|sort|uniq|tr "\n" " "|sed "s/^/DIRS=/" > $GITHUB_ENV

      # 変更のあったプロジェクトディレクトリに入ってビルドを繰り返す
      - name: Build
        run: |
          echo ">DIRS"
          echo "[${{ env.DIRS }}]"
          echo ">FOR"
          for dir in ${{ env.DIRS }}; do
            echo "[$dir]"
            cd $dir
            npm install
            slidev build --base /slidevtest/$dir/ --out ../docs/$dir/
            cd ..
          done

      - name: git setting
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit files
        run: |
          git add .
          git commit -m "update docs"
          git push
